name: Create Build and Release

on:
  workflow_dispatch: # ✅ Only manual trigger

# on:
  # push:
    # branches:
      # - 'master'
  # workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Remove unneeded installs (MSVC is pre-installed)
      - name: Install Dependencies (Windows)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress

      # ✅ Create Build Directory
      - name: Create Build Directory
        run: mkdir build

      # ✅ Build with MSVC (Windows)
      - name: Build Project (Windows with MSVC)
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      # ✅ Debug Build Output
      - name: Debug Build Output (Windows)
        run: dir build\bin\Release

      # ✅ Fix Artifact Upload Path
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dna-hidden-repeat-detector-windows
          path: build/bin/Release/dna-hidden-repeat-detector.exe
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Install Dependencies for Linux (GCC, CMake)
      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      # ✅ Create Build Directory
      - name: Create Build Directory
        run: mkdir -p build

      # ✅ Build with GCC (Linux)
      - name: Build Project (Linux with GCC)
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      # ✅ Debug Build Output
      - name: Debug Build Output (Linux)
        run: ls -al build/

      # ✅ Upload Linux Artifact
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dna-hidden-repeat-detector-linux
          path: build/bin/dna-hidden-repeat-detector
          if-no-files-found: error

  release:
    needs: [build-windows, build-linux] # ✅ Wait for both builds to complete
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Fix Download Path
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: dna-hidden-repeat-detector-windows
          path: build/windows/

      # ✅ Download Linux Build
      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: dna-hidden-repeat-detector-linux
          path: build/linux/

      # ✅ Create Dynamic Tag Name (based on commit hash or timestamp)
      - name: Generate Tag Name
        id: generate_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d-%H%M%S')"
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      # ✅ Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/dna-hidden-repeat-detector.exe
          tag_name: ${{ env.tag_name }}
          name: Release ${{ env.tag_name }}
          body: |
            ## 🚀 Changes in this release:
            - Built with MSVC for Windows and GCC for Linux.
            - Direct executable — no external dependencies.
            - Enhanced stability and speed.
            - Enhanced compatibility across platforms.           
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
