name: Create Build and Release

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies (Windows)
        run: |
          choco install cmake
          choco install visualstudio2022buildtools --version=17.10
          choco install visualstudio2022-workload-vctools

      - name: Create Build Directory
        run: mkdir build

      - name: Build Project (Windows with MSVC)
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Debug Build Output (Windows)
        run: dir build\

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dna-hidden-repeat-detector-windows
          path: build/Release/dna-hidden-repeat-detector.exe
          if-no-files-found: error

  release:
    needs: build-windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: dna-hidden-repeat-detector-windows
          path: build/windows/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/windows/dna-hidden-repeat-detector.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release:
            - Built with MSVC for better Windows compatibility.
            - Direct executable — no external dependencies.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
