name: Create Release Pipeline

on:
  push:
    branches:
      - 'master'  # Trigger only on push to master branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Clean up existing build directory
        run: |
          if [ -d "build" ]; then rm -rf build; fi

      - name: Create Build Directory
        run: mkdir build

      - name: Build Project
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make

      # ✅ Debug step to check generated files
      - name: Debug Build Files
        run: |
          echo "Listing build directory:"
          ls -l build/

      # ✅ Upload only the executable, not CMake files!
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dna-hidden-repeat-detector
          path: |
            build/dna-hidden-repeat-detector  # ✅ Ensure the file exists!

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dna-hidden-repeat-detector
          path: build/

      # ✅ Upload only the final executable in the release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dna-hidden-repeat-detector  # ✅ Ensure the file exists!
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release:
            - Auto-generated release using GitHub Actions.
            - Built using CMake and Make.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
